name: Build Pipeline
# Runs on all pushes that pass checks and are merged into main.
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"
  #   paths-ignore:
  #     - .github/**
  #     - README.md
  #     - 2.txt
  #     - some_folder/**
jobs:
  # check if only certain files were changed
  # don't build if non-structural changes were made
  file-check:
    runs-on: ubuntu-20.04
    steps:
      - name: do stuff
        run: echo ***********hello***********
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Set up python
      #   # Setup correct python version
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"
      #     cache: "pip"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      # - name:
      #     compare files
      #     # look at files from above
      #     # look at files from ignore-files.txt
      #     # if all files from above are contained in ignore-files.txt then ignore this step
      #   run: |
      #     python .github/workflows/compare.py ${{ steps.changed-files.outputs.all_changed_files }}
