name: cache-pip-pr
on:
  pull_request:
    branches:
      - main
jobs:
  # Run the black formatter (for Python code)
  pip:
    # define the operating system for the jobs to run on
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Setup python with our build version, no build matrix
      - name: Set up python
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"

      - name: Cache packages
        id: python_cache
        uses: actions/cache@v3
        with:
          path: venv
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

      - if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          # Check if venv exists (restored from secondary keys if any, and delete)
          # You might not need this line if you only have one primary key for the venv caching
          # I kept it in my code as a fail-safe
          if [ -d "venv" ]; then rm -rf venv; fi

          # Re-create the venv
          python3 -m venv venv

          # Install dependencies
          venv/bin/python3 -m pip install -r requirements.txt
