name: do me first
# Runs on all pushes against main.
on:
  pull_request:
    branches:
      - "main"
jobs:
  file-check:
    runs-on: ubuntu-20.04
    steps:
      - name: do stuff 123
        run: echo hello123
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        # https://github.com/tj-actions/changed-files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
