name: do me first
# Runs on all pushes against main.
on:
  pull_request:
    branches:
      - "main"
jobs:
  file-check:
    runs-on: ubuntu-20.04
    steps:
      - name: do stuff 123
        run: echo hello123
      - name: try to fail
        run: exit 1
