# name: do me first 123
# # Runs on all pushes against main.
# on:
#   pull_request:
#     branches:
#       - "main"
# jobs:
#   file-check:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Get changed files in the docs folder
#         id: changed-files-specific
#         uses: tj-actions/changed-files@v35
#         with:
#           files: |
#             requirements.txt

#       - name: Run step if requirements.txt has changes
#         if: steps.changed-files-specific.outputs.any_changed == 'true'
#         run: |
#           echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"
