name: do me last0
# Runs on all PRs (against main) after "do me first" has completed
on:
  workflow_run:
    workflows: ["do me first"]
    types:
      - completed
jobs:
  depth_zero:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        # https://github.com/tj-actions/changed-files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
  depth_one:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Get changed files
        # https://github.com/tj-actions/changed-files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
  depth_two:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        # https://github.com/tj-actions/changed-files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
