name: do me last
# Runs on all PRs (against main) after "do me first" has completed
on:
  workflow_run:
    workflows: ["do me first"]
    types:
      - completed
jobs:
  checkiboi:
    name: Checkiboi
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: do something
        run: echo *****THIS SHOULD SHOW UP LAST0*****
