name: do me last
# Runs on all pushes that pass checks and are merged into main.
on:
  pull_request:
    branches:
      - "main"
jobs:
  checkiboi:
    runs-on: ubuntu-20.04
    steps:
      - name: echo ref
        run: echo *****${{ github.ref }}*****
      - name: Wait for other workflows
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: "do me first"
      - name: do something
        run: echo *****THIS SHOULD SHOW UP LAST*****
