name: do me last 123
# Runs on all PRs (against main) after "do me first" has completed
on:
  workflow_run:
    workflows: ["do me first"]
    types:
      - completed
jobs:
  on_success:
    name: on success
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: do something
        run: echo *****I PASSED*****
      - name: Verify Changed files
        # https://github.com/marketplace/actions/verify-changed-files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
            requirements.txt
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"
  on_failure:
    name: on failure
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: do something
        run: echo *****I FAILED*****
