name: do me last
# Runs on all pushes that pass checks and are merged into main.
on:
  workflow_run:
    workflows: ["do me first"]
    types:
      - completed
jobs:
  checkiboi:
    name: Checkiboi
    runs-on: ubuntu-20.04
    steps:
      - name: do something
        run: echo *****THIS SHOULD SHOW UP LAST0*****
