name: Python Envs
# Runs on all pushes against main.
on:
  workflow_dispatch:

jobs:
  python-envs:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up python
        # Setup correct python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.9"

      - name: Python Version
        shell: bash
        run: |
          python --version

      - name: Python
        shell: bash
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/python_envs.py

      - name: Echo env vars
        shell: bash
        env:
          NEW_ENV_VAR: ${{ env.NEW_ENV_VAR }}
        run: |
          echo $NEW_ENV_VAR
