name: Python Envs
# Runs on all pushes against main.
on:
  workflow_dispatch:

jobs:
  python-envs:
    runs-on: ubuntu-20.04
    steps:
      - name: Python Version
        shell: bash
        run: |
          python --version

      - name: Set up python
        # Setup correct python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.9"

      - name: Python
        shell: python
        run: |
          import os

          # Get the path to the GITHUB_ENV file
          env_file_path = os.getenv('GITHUB_ENV')

          # Check if the GITHUB_ENV file path is set
          if env_file_path:
              # Open the GITHUB_ENV file in append mode
              with open(env_file_path, 'a') as env_file:
                  # Write the environment variable to the file
                  env_file.write("NEW_ENV_VAR=1234\n")
          else:
              print("GITHUB_ENV file path not found")

      - name: Echo env vars
        shell: bash
        env:
          NEW_ENV_VAR: ${{ env.NEW_ENV_VAR }}
        run: |
          echo $NEW_ENV_VAR
