name: Selectable Shell
# Runs on all pushes against main.
on:
  workflow_dispatch:

jobs:
  shells:
    runs-on: ubuntu-20.04
    steps:
      - name: Python Version
        shell: bash
        run: |
          python --version

      - name: Set up python
        # Setup correct python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.9"
          cache: "pip"

      - name: Python
        shell: python
        run: |
          import sys
          print(sys.version)

      - name: Python3
        shell: python3
        run: |
          import sys
          print(sys.version)

      - name: Python3.10
        shell: python3.10
        run: |
          import sys
          print(sys.version)

      - name: Python3.10.9
        shell: python3.10.9
        run: |
          import sys
          print(sys.version)
