name: test
# Runs on all pushes against main.

on:
  pull_request:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-20.04
    steps:
      # - name: first
      #   run: |
      #     exit 0
      # - name: echo contexts
      #   # env:
      #   # LABELS: ${{ github.event.pull_request.labels }}
      #   id: echo-contexts
      #   run: |
      #     echo ${{ toJson(github.event.pull_request.labels) }} | jq '.[].name' | grep 'bug'
      - name: add hotfix label
      - name: auto approve hotfixes
        if: contains(github.event.pull_request.labels.*.name, 'hotfix')
        run: |
          curl -X POST \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -d '{
              "event": "APPROVE"
            }'
