name: test
# Runs on all pushes against main.

on:
  pull_request:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-20.04
    steps:
      # - name: first
      #   run: |
      #     exit 0
      # - name: echo contexts
      #   # env:
      #   # LABELS: ${{ github.event.pull_request.labels }}
      #   id: echo-contexts
      #   run: |
      #     echo ${{ toJson(github.event.pull_request.labels) }} | jq '.[].name' | grep 'bug'
      - name: check bug label status
        if: contains(github.event.pull_request.labels.*.name, 'bug')
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{
              "reviewers": [],
              "team_reviewers": []
            }'
